<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>位置管理 - 添加</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">


    <link rel="stylesheet" href="<?php echo $host;?>/static/market/add&edit&show.css?hash=17398754">
    <style type="text/css">
        .content {
            width: 100%;
            height: 500px;
            display: flex;
            flex-direction: column;
            justify-content: space-around;
            margin-top: 0px;
        }

        .content span {
            margin: 10px 0 20px 10%;
            font-size: 16px;
        }

        .content textarea {
            padding: 10px;
            width: 60%;
            margin-left: 10%;
            border-radius: 8px;
        }

        .content input[type='submit'] {
            width: 150px;
            height: 42px;
            background-color: #38adff;
            border: none;
            border-radius: 3px;
            line-height: 42px;
            font-size: 15px;
            color: #fff;
            margin-left: 40%;
            cursor: pointer;
        }
    </style>
</head>
<body>
<!--html-->
<div id="root">
    <div class="back-btn"></div>
    <div class="title">位置类别 - 添加</div>
    <!--form表单-->
    <form id="form" action="/market/guidelineac_add_post/add_post"  method="post">
        <input type="hidden" id="marketId" name="marketId" value="<?php echo $marketId; ?>">
        <input type="hidden" id="typeParentId" name="typeParentId" value="<?php echo $typeParentId; ?>">
        <input type="hidden" id="fieldTypeId" name="fieldTypeId" value="<?php echo $fieldTypeId; ?>">

        <input type="hidden" id="" name="redirect" value="/market/guidelineac?typeParentId=<?php echo $typeParentId; ?>&fieldTypeId=<?php echo $fieldTypeId; ?>">
        <input type="hidden" id="" name="field_id[47]" value="<?php echo date('Y-m-d H:i:s'); ?>">

        <!--文字信息行-->
        <div class="text-row">
            <div class="column">
                <span class="text">类别名称：</span>
                <input type="text" name="field_id[46]" required value="">
            </div>
            <div class="column">
                <span class="text">排序：</span>
                <input type="text" name="field_id[44]" required value="0">
            </div>
        </div>
        <div class="line-row"></div>
        <!--提交按钮行-->
        <div class="button-row">
            <input type="submit" value="提交">
        </div>
    </form>

</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>

<script src="<?php echo $host;?>/static/market/jxposition_type/add.js?hash=924957357"></script>
</body>
</html>