
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>智慧农贸管理平台 - 媒体广告设置</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">

    <link rel="stylesheet" href="<?php echo $host;?>/static/market/common.css?hash=755293083">
</head>
<body>
<!--html-->
<div id="root">
    <div class="nav-wrapper">
        <ul class="nav">
            <li><a href="/market/screen_menuac/index/parent_id/8.html">触摸屏栏目管理</a></li>
            <li><a href="/market/screen_infosac/index/parent_id/8.html">触摸屏信息管理</a></li>
            <li class="active" data-pid="8"><a href="/market/adv_typeac/index/parent_id/8.html">触摸屏广告设置</a></li>
            <li><a href="/market/market_imgac/index/parent_id/8.html">触摸屏图片广告</a></li>
            <li><a href="/market/market_advac/index/parent_id/8.html">触摸屏视频广告</a></li>
            <li><a href="/market/single_pageac/index/parent_id/8.html">触摸屏单页广告</a></li>
            <li><a href="/market/stall_advac/index/parent_id/8.html">商户广告管理</a></li>
            <li><a href="/market/floor_mapac/index/parent_id/8.html">触摸屏市场地图</a></li>
            <li><a href="/market/guide_priceac/index/parent_id/8.html">商户价位指导</a></li>
            <li><a href="/market/merchant_goodsac/index/parent_id/8.html">商户菜品管理</a></li>
            <li><a href="/market/screenac/index/parent_id/8.html">分屏支付显示设置</a></li>
            <li><a href="/market/market_setingac/index/parent_id/8.html">分屏广告图片</a></li>
        </ul>
    </div>
    <div class="content-wrapper">
        <!--操作-->
        <div class="operate">
            <div class="left">
                <span>媒体广告设置</span>
            </div>
            <div class="right">

            </div>
        </div>
        <!---列表-->
        <div class="list">
            <table border="1">
                <thead>
                <tr>
                    <th>农贸市场</th>
                    <th>广告类型</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>

                <tr>
                    <td>林鲲菜场</td>
                    <td>
                        <label><input type="radio"  value="1" name="type">图片</label>
                        <label><input type="radio" checked value="2" name="type">视频</label>
                    </td>
                    <td><button id="btn_edit">修改</button> </td>
                </tr>

                </tbody>
            </table>
        </div>
        <!--分页-->

    </div>
</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>

<script src="<?php echo $host;?>/static/market/advtype/index.js?hash=850889146"></script>
</body>
</html>
