
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>代办事项 - 添加</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/cropper.min.css">

    <link rel="stylesheet" href="<?php echo $host;?>/static/market/add&edit&show.css?hash=864891394">
    <style>
        .text-row .column {
            display: flex;
            width: unset;
        }

        .content {
            width: 650px;
            height: 230px;
            margin-top: 10px;
            border-radius: 9px;
            border:1px solid #eaeaea;
            outline: none;
            padding: 10px;
            font-size: 15px;
            color: #4a4a4a;
            font-family: initial;
            resize: none;
        }
    </style>
</head>
<body>
<!--html-->
<div id="root">
    <div class="back-btn"></div>
    <div class="title">待办事项 - 添加</div>
    <!--form表单-->
    <form id="form" action="/market/guidelineac_add_post/add_post" enctype="multipart/form-data" method="post">
        <input type="hidden" id="marketId" name="marketId" value="<?php echo $marketId; ?>">
        <input type="hidden" id="typeParentId" name="typeParentId" value="<?php echo $typeParentId; ?>">
        <input type="hidden" id="fieldTypeId" name="fieldTypeId" value="<?php echo $fieldTypeId; ?>">
        <input type="hidden" id="" name="redirect" value="/market/guidelineac?typeParentId=<?php echo $typeParentId; ?>&fieldTypeId=<?php echo $fieldTypeId; ?>">

        <input type="hidden" id="" name="field_id[181]" value="<?php echo date('Y-m-d'); ?>">
        <!--文字信息行-->
        <div class="text-row">
            <div class="column">
                <span class="text">事项：</span>
                <input type="text" name="field_id[222]" required>
            </div>
        </div>

        <div class="text-row">
            <div class="column">
                <span class="text">日期：</span>
                <input type="text" id="date" name="field_id[223]" required autocomplete="off">
            </div>
        </div>
        <div class="text-row">
            <div class="column">
                <span class="text">内容：</span>
                <textarea name="field_id[224]" class="content"></textarea>
            </div>
        </div>
        <!--分割线-->
        <div class="line-row"></div>
        <!--提交按钮行-->
        <div class="button-row">
            <input type="submit" value="提交">
        </div>
    </form>
</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>
<script src="<?php echo $host;?>/static/lib/laydate/laydate.js"></script>

<script src="<?php echo $host;?>/static/market/backlog/add.js?hash=659568039"></script>
</body>
</html>