
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>红黑榜： - 添加</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">

    <link rel="stylesheet" href="<?php echo $host;?>/static/market/add&edit&show.css?hash=484766452">
</head>
<body>
<!--html-->
<div id="root">
    <div class="back-btn"></div>
    <div class="title">红黑榜： - 添加</div>
    <!--form表单-->
    <form id="form" action="/market/guidelineac_add_post/add_post" method="post">
        <input type="hidden" id="marketId" name="marketId" value="<?php echo $marketId; ?>">
        <input type="hidden" id="typeParentId" name="typeParentId" value="<?php echo $typeParentId; ?>">
        <input type="hidden" id="fieldTypeId" name="fieldTypeId" value="<?php echo $fieldTypeId; ?>">
        <input type="hidden" id="eventName" name="eventName" value="tall.add">

        <input type="hidden" id="" name="redirect" value="/market/guidelineac?typeParentId=<?php echo $typeParentId; ?>&fieldTypeId=<?php echo $fieldTypeId; ?>">
        <!--文字信息行-->
        <div class="text-row">
            <div class="column">
                <span class="text">标题：</span>
                <input type="text" name="field_id[240]" required>
            </div>
            <div class="column">
            </div>
        </div>
        <!--富文本编辑行-->
        <div class="article-row">
            <script type="text/plain" id="myEditor" name="field_id[244]" style="width:100%;height:300px;"></script>
        </div>
        <!--分割线-->
        <div class="line-row"></div>
        <!--提交按钮行-->
        <div class="button-row">
            <input type="submit" value="提交">
        </div>
    </form>
</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>
<script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/ueditor.all.min.js"></script>
<script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/lang/zh-cn/zh-cn.js"></script>

<script src="<?php echo $host;?>/static/market/yjyredblack/add.js?hash=801942415"></script>
</body>
</html>