<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>市场活动 - 添加</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">

    <link rel="stylesheet" href="<?php echo $host;?>/static/market/add&edit&show.css?hash=408556540">
</head>
<body>
<!--html-->
<div id="root">
    <div class="back-btn"></div>
    <div class="title">市场制度 - 修改</div>
    <!--form表单-->
    <form id="form" action="/market/guidelineac_edit_post/edit_post" method="post">
        <input type="hidden" id="marketId" name="marketId" value="<?php echo $marketId; ?>">
        <input type="hidden" id="typeParentId" name="typeParentId" value="<?php echo $typeParentId; ?>">
        <input type="hidden" id="fieldTypeId" name="fieldTypeId" value="<?php echo $fieldTypeId; ?>">
        <input type="hidden" id="uid" name="uid" value="<?php echo $uid; ?>">
        <input type="hidden" id="" name="redirect" value="/market/guidelineac?fieldTypeId=<?php echo $fieldTypeId; ?>">

        <!--文字信息行-->
        <div class="text-row">
            <div class="column">
                <span class="text">活动名称：</span>
                <input type="text" name="field_id[24][<?php echo $data[24]['id']; ?>]" value="<?php echo $data[24]['field_value']; ?>" required>
            </div>
            <div class="column">
                <span class="text">发布单位：</span>
                <input type="text" name="field_id[287][<?php echo $data[287]['id']; ?>]" value="<?php echo $data[287]['field_value']; ?>" required>
            </div>

        </div>
        <div class="text-row">
            <div class="column">
                <span class="text">开始时间：</span>
                <input type="text" name="field_id[288][<?php echo $data[288]['id']; ?>]" class="date" id="date-start" value="<?php echo $data[288]['field_value']; ?>" readonly>
            </div>
            <div class="column">
                <span class="text">结束时间：</span>
                <input type="text" name="field_id[289][<?php echo $data[289]['id']; ?>]" class="date" id="date-end" value="<?php echo $data[289]['field_value']; ?>" readonly>
            </div>
        </div>
        <!--富文本编辑行-->
        <div class="article-row">
            <script type="text/plain" id="myEditor" name="field_id[26][<?php echo $data[26]['article_id']; ?>]" style="width:100%;height:300px;"><?php echo $data[26]['field_value']; ?></script>
            </div>
            <!--分割线-->
            <div class="line-row"></div>
                <!--提交按钮行-->
                <div class="button-row">
                <input type="submit" value="提交">
                </div>
                </form>
                </div>
                <!--javascript-->
                <script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>
            <script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/ueditor.config.js"></script>
            <script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/ueditor.all.min.js"></script>
            <script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/lang/zh-cn/zh-cn.js"></script>
            <script src="<?php echo $host;?>/static/lib/laydate/laydate.js"></script>

            <script src="<?php echo $host;?>/static/market/activities/edit.js?hash=574048585"></script>
</body>
</html>