
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>市场活动 - 添加</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">

    <link rel="stylesheet" href="<?php echo $host;?>/static/market/add&edit&show.css?hash=589153033">
</head>
<body>
<!--html-->
<div id="root">
    <div class="back-btn"></div>
    <div class="title">市场制度 - 修改</div>
    <!--form表单-->
    <form id="form" action="/market/guidelineac_edit_post/edit_post" method="post">

        <input type="hidden" id="marketId" name="marketId" value="<?php echo $marketId; ?>">
        <input type="hidden" id="typeParentId" name="typeParentId" value="<?php echo $typeParentId; ?>">
        <input type="hidden" id="fieldTypeId" name="fieldTypeId" value="<?php echo $fieldTypeId; ?>">
        <input type="hidden" id="uid" name="uid" value="<?php echo $uid; ?>">

        <input type="hidden" id="" name="redirect" value="/market/guidelineac?fieldTypeId=<?php echo $fieldTypeId; ?>">

        <input type="hidden" id="" name="field_id[208][<?php echo $data[208]['id']; ?>]" value="<?php echo date('Y-m-d'); ?>">
        <!--文字信息行-->
        <div class="text-row">
            <div class="column">
                <span class="text">培训名称：</span>
                <input type="text" name="field_id[206][<?php echo $data[206]['id']; ?>]" value="<?php echo $data[206]['field_value']; ?>"  required>
            </div>
            <div class="column">
                <span class="text">培训单位：</span>
                <input type="text" name="field_id[1][<?php echo $data[207]['id']; ?>]" value="<?php echo $data[207]['field_value']; ?>" required>
            </div>

        </div>
        <div class="text-row">
            <div class="column">
                <span class="text">培训时间：</span>
                <input type="text" name="field_id[208][<?php echo $data[208]['id']; ?>]" value="<?php echo $data[208]['field_value']; ?>" readonly>
            </div>
        </div>
        <!--富文本编辑行-->
        <div class="article-row">
            <script type="text/plain" id="myEditor" name="field_id[352][<?php echo $data[352]['article_id']; ?>]" style="width:100%;height:300px;"><?php echo $data[352]['field_value']; ?></script>
        </div>
        <!--分割线-->
        <div class="line-row"></div>
        <!--提交按钮行-->
        <div class="button-row">
            <input type="submit" value="提交">
        </div>
    </form>
</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>
<script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/ueditor.all.min.js"></script>
<script type="text/javascript" src="<?php echo $host;?>/static/lib/ueditor/lang/zh-cn/zh-cn.js"></script>
<script src="<?php echo $host;?>/static/lib/laydate/laydate.js"></script>

<script src="<?php echo $host;?>/static/market/train_exchange/edit.js?hash=715786312"></script>
</body>
</html>