<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>智慧农贸管理平台 -摊位类型</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/market/common.css?hash=100536413"></head>
<body>
<!--html-->
<div id="root">
    <div class="nav-wrapper">
        <ul class="nav">
            <li class="active" data-parent="3"><a
                    href="/market/stall_typeac/index/parent_id/3.html">摊位类型</a></li>
            <li><a href="/market/sx_stallac/index/parent_id/3.html">摊位管理</a></li>
            <li><a href="/market/sx_merchantac/index/parent_id/3.html">商户管理</a></li>
            <li><a href="/market/sx_contractac/index/parent_id/3.html">合同管理	</a></li>
            <li><a href="/market/sx_history_archivesac/index/parent_id/3.html">历年档案</a></li>
        </ul>
    </div>
    <div class="content-wrapper">
        <div class="operate">
            <div class="left">
                <span>摊位类型：</span>
                <input type="text" id="cate_name" value="">
                <button id="query_btn">查询</button>
            </div>
            <div class="right">
                <button id="btn_add">添加</button>
                <button id="btn_edit">修改<div class="tips">您还没有选择任何内容</div></button>
                <button id="btn_del">删除<div class="tips">您还没有选择任何内容</div></button>
                <!-- <button id="btn_exports">导出</button> -->
            </div>
        </div>
        <div class="list">
            <table border="1">
                <thead>
                <tr>
                    <th>
                        <input type="checkbox" id="check-all">
                    </th>
                    <th>摊位类型</th>
                    <th>类型编码</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="497">
                    </td>
                    <td>肉,蛋类</td>
                    <td>002</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="496">
                    </td>
                    <td>蔬菜类</td>
                    <td>001</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="498">
                    </td>
                    <td>海鲜类</td>
                    <td>003</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="499">
                    </td>
                    <td>活鱼水产</td>
                    <td>004</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="500">
                    </td>
                    <td>冷冻和水产食品</td>
                    <td>005</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="501">
                    </td>
                    <td>酱菜</td>
                    <td>006</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="502">
                    </td>
                    <td>熟食</td>
                    <td>007</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="503">
                    </td>
                    <td>土特产(笋菇干货)</td>
                    <td>008</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="504">
                    </td>
                    <td>食杂</td>
                    <td>009</td>

                </tr>
                <tr>
                    <td>
                        <input type="checkbox" class="i-checks" name="id" value="505">
                    </td>
                    <td>日用品</td>
                    <td>010</td>

                </tr>
                </tbody>
            </table>
        </div>

        <div class="page-wrapper">
            <div class="page-list"><ul class="pagination"><li class="disabled"><span>&laquo;</span></li> <li class="active"><span>1</span></li><li><a href="/market/stall_typeac/index/parent_id/3.html?parent_id=3&amp;page=2">2</a></li> <li><a href="/market/stall_typeac/index/parent_id/3.html?parent_id=3&amp;page=2">&raquo;</a></li></ul></div>
            <div class="total">共2页</div>
            <div class="go">去第<input type="text" id="page" value="1">页
                <button id="sure">确定</button>
            </div>
        </div>
        <!--删除确认框-->
        <div class="confirm">
            <div class="text">确定要删除吗？</div>
            <div class="btn-wrapper">
                <button id="del-confirm">确定</button>
                <button id="del-cancel">取消</button>
            </div>
        </div>
        <!--删除失败提示-->
        <div class="toast">
            <div class="text">删除失败!</div>
        </div>
    </div>

</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>
<script src="<?php echo $host;?>/static/lib/laydate/laydate.js"></script>
<script src="<?php echo $host;?>/static/market/stall_type/index.js?hash=309635603"></script>
</body>
</html>
