<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>智慧农贸管理平台 - 媒体广告设置</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">

    <link rel="stylesheet" href="<?php echo $host;?>/static/market/common.css?hash=868971770">
</head>
<body>
<!--html-->
<div id="root">
    <div class="nav-wrapper">
        <ul class="nav">
            <li class="active" data-pid="84"><a href="/market/yjy_adv_typeac/index/parent_id/84.html">广告机设置</a></li>
            <li><a href="/market/yjy_advac/index/parent_id/84.html">滚动图片</a></li>
            <li><a href="/market/yjy_marqueeac/index/parent_id/84.html">滚动文字</a></li>
            <li><a href="/market/yjy_logoac/index/parent_id/84.html">logo设置</a></li>
            <li><a href="/market/yjy_videoac/index/parent_id/84.html">各类视频</a></li>
            <li><a href="/market/yjy_circularac/index/parent_id/84.html">图文通告</a></li>
            <li><a href="/market/yjy_redblackac/index/parent_id/84.html">通报红黑榜</a></li>
            <li><a href="/market/yjy_institutionac/index/parent_id/84.html">管理制度</a></li>
        </ul>
    </div>
    <div class="content-wrapper">
        <!--操作-->
        <div class="operate">
            <div class="left">
                <span>媒体广告设置</span>
            </div>
            <div class="right">

            </div>
        </div>
        <!--列表-->
        <div class="list">
            <table border="1">
                <thead>
                <tr>
                    <th>农贸市场</th>
                    <th>广告类型</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>

                <tr>
                    <td>金沙市场</td>
                    <td>
                        <label><input type="radio" checked value="1" name="type">滚动图片</label>&nbsp;&nbsp;&nbsp;&nbsp;
                        <label><input type="radio"  value="2" name="type">分类视频</label>&nbsp;&nbsp;&nbsp;&nbsp;
                        <label><input type="radio"  value="3" name="type">图片通告</label>&nbsp;&nbsp;&nbsp;&nbsp;
                        <label><input type="radio"  value="4" name="type">红黑榜</label>&nbsp;&nbsp;&nbsp;&nbsp;
                        <label><input type="radio"  value="5" name="type">市场制度</label>
                    </td>
                    <td><button id="btn_edit">修改</button> </td>
                </tr>

                </tbody>
            </table>
        </div>
        <!--分页-->

    </div>
</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>

<script src="<?php echo $host;?>/static/market/yjyadvtype/index.js?hash=448672838"></script>
</body>
</html>
