<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>智慧农贸管理平台 - 管理制度</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/market/common.css?hash=81903969"></head>
<body>
<!--html-->
<div id="root">
    <div class="nav-wrapper">
        <ul class="nav">
            <li class="active" data-pid="9"><a href="/market/monitorac/index/parent_id/9.html">实时监控</a></li>
            <li class="active" data-pid="9"><a href="/market/monitorac/index/parent_id/9.html">录像回放</a></li>
        </ul>
    </div>
    <div class="content-wrapper">
        <h2>商铺监控</h2>
        <br>
        <div id="nvr-zone"></div>
    </div>
</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>

<script src="<?php echo $host;?>/static/market/monitor/index.js?hash=61555131"></script></body>
</html>