<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>智慧农贸管理平台 - 管理制度</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/reset.css">
    <link rel="stylesheet" href="<?php echo $host;?>/static/lib/css/font-awesome.min.css">

    <link rel="stylesheet" href="<?php echo $host;?>/static/market/common.css?hash=62686539">
</head>
<body>
<!--html-->
<div id="root">
    <div class="nav-wrapper">
        <ul class="nav">
            <li class="active" data-pid="8"><a href="/market/screen_menuac/index/parent_id/8.html">触摸屏栏目管理</a></li>
            <li><a href="/market/screen_infosac/index/parent_id/8.html">触摸屏信息管理</a></li>
            <li><a href="/market/adv_typeac/index/parent_id/8.html">触摸屏广告设置</a></li>
            <li><a href="/market/market_imgac/index/parent_id/8.html">触摸屏图片广告</a></li>
            <li><a href="/market/market_advac/index/parent_id/8.html">触摸屏视频广告</a></li>
            <li><a href="/market/stall_advac/index/parent_id/8.html">商户广告管理</a></li>
            <li><a href="/market/floor_mapac/index/parent_id/8.html">触摸屏市场地图</a></li>
            <li><a href="/market/guide_priceac/index/parent_id/8.html">商户价位指导</a></li>
            <li><a href="/market/merchant_goodsac/index/parent_id/8.html">商户菜品管理</a></li>
            <li><a href="/market/screenac/index/parent_id/8.html">分屏支付显示设置</a></li>
            <li><a href="/market/market_setingac/index/parent_id/8.html">分屏广告图片</a></li>
        </ul>
    </div>
    <div class="content-wrapper">
        <!--操作-->
        <!--列表-->
        <div class="list">
            <table border="1">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>栏目名称</th>
                </tr>
                </thead>
                <tbody>
                <tr class="gradeA">
                    <td>9</td>
                    <td>行业规范</td>
                </tr>
                <tr class="gradeA">
                    <td>10</td>
                    <td>市场动态</td>
                </tr>
                <tr class="gradeA">
                    <td>11</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--领导关怀</td>
                </tr>
                <tr class="gradeA">
                    <td>13</td>
                    <td>市场介绍</td>
                </tr>
                <tr class="gradeA">
                    <td>14</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--市场简介</td>
                </tr>
                <tr class="gradeA">
                    <td>16</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--通知公告</td>
                </tr>
                <tr class="gradeA">
                    <td>18</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--管理制度</td>
                </tr>
                <tr class="gradeA">
                    <td>23</td>
                    <td>科普农贸</td>
                </tr>
                <tr class="gradeA">
                    <td>25</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--健康饮食</td>
                </tr>
                <tr class="gradeA">
                    <td>26</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--生活窍门</td>
                </tr>
                <tr class="gradeA">
                    <td>30</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--市场荣誉</td>
                </tr>
                <tr class="gradeA">
                    <td>33</td>
                    <td>服务指南</td>
                </tr>
                <tr class="gradeA">
                    <td>34</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--街道服务</td>
                </tr>
                <tr class="gradeA">
                    <td>35</td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|--家政服务</td>
                </tr>
                </tbody>
            </table>
        </div>
        <!--分页-->
    </div>
</div>
<!--javascript-->
<script src="<?php echo $host;?>/static/lib/js/jquery.1.11.3.js"></script>
<script src="<?php echo $host;?>/static/market/screen_menu/index.js?hash=902727861"></script></body>
</html>