<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>市场制度 - 详情</title>
    <meta name="keywords" content="智慧农贸">
    <meta name="description" content="智慧农贸">
    <!--css-->
    <link rel="stylesheet" href="/static/lib/css/reset.css">
    <link rel="stylesheet" href="/static/lib/css/font-awesome.min.css">

    <link rel="stylesheet" href="/static/market/add&edit&show.css?hash=12677980">
</head>
<body>
<!--html-->
<div id="root">
    <div class="back-btn"></div>
    <div class="title">市场制度 - 详情</div>

    <!--form表单-->
    <form id="form" action="/market/guidelineac_edit" method="get">
        <input type="hidden" name="id" value="<?php echo $uid; ?>">
        <input type="hidden" name="fieldTypeId" value="<?php echo $fieldTypeId; ?>">
        <input type="hidden" name="typeParentId" value="<?php echo $typeParentId; ?>">
        <input type="hidden" name="marketId" value="<?php echo $marketId; ?>">

        <!--文字信息行-->
        <div style="padding: 0 150px">
            <p style="text-align: center"><?php echo $data[$field_id]['field_value'] ?></p><br>
            <p>　　
                <?php echo $content ?>
            </p>
        </div>

        <!--分割线-->
        <div class="line-row"></div>
        <!--提交按钮行-->
        <div class="button-row">
            <input type="submit" value="编辑">
        </div>
    </form>
</div>
<!--javascript-->
<script src="/static/lib/js/jquery.1.11.3.js"></script>

<script src="/static/market/guideline/show.js?hash=430432847"></script>
</body>
</html>